### PR TITLE
Updated MANIFEST.in to include the LICENSE, and added the LICENSE headers to the .py files for rawes

### PR DESCRIPTION
**Pull request by neogenix**
Updated MANIFEST.in to include the LICENSE, and added the LICENSE headers to the .py files for rawes, although at this point they're pointed to [Dan Noble]

### CODE REVIEW

**Comment by neogenix** [comment]
Added more stuff to the .gitignore.

**Comment by neogenix** [comment]
Added anyjson as an option for speed / compat.

**Comment by neogenix** [comment]
Another batch of changes to setup.py, and added a CHANGES.md.

**Comment by neogenix** [comment]
Much PEP8 fixering, and some changes to the overall layout.

**Comment by neogenix** [comment]
Btw, for sanity sake, all tests run as expected (I did see the test suite fail when ES didn't keep up with the initial write, but re-running multiple times works fine) 

uslt-205774:rawes patrick.ancillotti$ nosetests

## ....

Ran 4 tests in 1.281s

OK

**Comment by dwnoble** [comment]
Thanks very much for all of these changes - i've merged them all in, but I changed the file headers to use my company name, and added a CONTRIBUTORS.md file.

About the test suites.. Hmm.  Maybe the index wasn't getting refreshed fast enough?  It looks like I forgot to add refresh : true to a few of the test functions (_test_document_update and _test_document_delete) - ill go ahead and add them now.

Dan

**Pull request merged**
