### PR TITLE
Naive datetime fix

### PR DESCRIPTION
**Pull request by adisbladis**
Datetime serialization for naive datetime objects was broken

### CODE REVIEW

**Comment by dwnoble** [comment]
@adisbladis - thanks for this pull request!

This new behavior will, given a datetime without a timezone, add a "UTC" timezone to it.  While this change itself is fine, my concern is that it may encourage bugs in people's code.  For example:

``` python
import rawes
import datetime
es = rawes.Elastic()
es.put('myindex/mytype/123', data = { "date" : datetime.datetime.now() })
```

This is an issue because my computer's local timezone is "America/New_York" - so datetime.datetime.now() will give me my current local time, but without an actual python timezone attached.  From the commit:

``` python
timezone("UTC").localize(obj).strftime('%Y-%m-%dT%H:%M:%SZ')
```

this native datetime will now be converted to UTC and will be the incorrect time (Went from America/New_York -> UTC without actually changing the time).  I feel like not allowing native datetime objects at all in rawes' default JSON encoder is worth the extra work it takes to explicitly assign a timezone so to avoid any chance of this bug.  But remember, if your use case ensures that you always have UTC times from the get-go, you can define a custom JSON encoder - one thing on the todo list is to add the "json_encoder" option the rawes.Elastic constructor to make specifying custom encoders easier.

Thanks again!

**Comment by dwnoble** [comment]
At the very minimum I'll make a prettier error message if someone uses a native datetime

**Comment by adisbladis** [comment]
You are absolutely right. 
The actual error is in the python datetime module, datetime.datetime.utcnow for example does not assign tzinfo even though I have explicitly said it's in utc.

I will use a custom json encoder instead and just pass the already encoded data to rawes.

@dwnoble Could you add issues for your todo-list, I would be happy to help :)

**Comment by dwnoble** [comment]
Sounds good, and I appreciate the offer for help!  I'll get to posting a few issues in the next day or so.

thanks again!

**Pull request closed without merging**
