### PR TITLE
Support complex URLs (+ API change + code cleanup)

### PR DESCRIPTION
**Pull request by nvie**
This provides:
- Support for parsing more complex URLs, see the extensive commit log on 70ac6eb0a0d685b78573cce0315cb24e43401d37 for details;
- A simpler API (see [usage](https://github.com/nvie/rawes/blob/master/README.md#usage))
- General code cleanup

### CODE REVIEW

**Comment by nvie** [comment]
Any progress or opinions on this patch, @humangeo?

**Comment by dwnoble** [comment]
Vincent - first of all thanks for the pull request, and sorry for the delay!  Been quite swamped with the day job lately, but I will get to this pull request this weekend.

Thanks again!

**Comment by nvie** [comment]
Sorry to ping you again, @dwnoble, but have you have time to look at this? I would love to upgrade my pinned version to a new rawes release instead of using my own fork in requirements.txt :)

**Comment by dwnoble** [comment]
Hey Vincent,

I did have some time to go over the request - here are my initial thoughts
1. this request breaks the unit tests! :)
2. It is currently possible to provide basic authentication parameters by doing something like:

``` python
es.get("posts/_search", auth=('user','pass'))
```

I realize this is not ideal as you'd have to pass it in on every request.  But I'll change it so you can specify arbitrary 'requests' args in the constructor as well as on a per request basis.  see: http://docs.python-requests.org/en/latest/user/authentication/
3. I want to keep port 9200 as the default for http.
4. 'path' argument removed from one too many places in readme
5. What is the issue with having 9500 be the default for thrift?  That is the port the thrift plugin defaults to for me.

can you address 1, 3, 4, and give me your thoughts on 5?
Thanks again!

**Comment by dwnoble** [comment]
Vincent: Sorry again for the long delay on this pull request.  I've made the above changes and merged in your request.

So, connecting to something like heroku will now look like this:

``` python
import rawes
es = rawes.Elastic('http://heroku-server.bonsai.io:80', auth=('username','password'))
es.post("new_index")
```

I ran a few tests with the username and password included in the url (like: http://username:password@heroku-server.bonsai.io) but it looks the python 'requests' (1.1.0) library does not support this syntax.  i.e., this would not even work for me:

``` python
import requests
requests.post("http://username:password@heroku-server.bonsai.io/new_index")
<Response [401]>
```

So for now, it can just go in the constructors auth kwarg.

Thanks!
Dan

**Pull request merged**
